### ISSUE TITLE
util/class not in rockspec, util/string missing

### ISSUE THREAD

**Issue by lebedov** [ClockVapor/collections#1]
util/class appears to needed by collection.lua, but isn't installed because it doesn't appear in the rockspec.

Also, when I tried to run `require 'array_list'` within luajit 2.1.0 after installing collections 1.0.0-3, luajit complained about not being able to find util/string. This module doesn't appear to be in the repo, however.

**Comment by ClockVapor** [comment]
Whoops! Thank you, fixing that now

**Comment by ClockVapor** [comment]
Okay, give it a shot. Thanks again; this is my first time making a rock 😀

**Comment by lebedov** [comment]
Works now. Thanks!
